version: "3.7"

services:
    securiskan-app:
        build: .
        container_name: securiskan-app
        entrypoint: sh cmd.sh
        volumes:
            - ./:/var/www/html
        ports:
            - "8080:80"
        depends_on:
            - securiskan-db
        networks:
            - securiskan-network
        environment:
            DB_CONNECTION: mysql
            DB_HOST: securiskan-db
            DB_PORT: 3306
            DB_DATABASE: securiskan
            DB_USERNAME: root
            DB_PASSWORD: root

    securiskan-db:
        image: mysql:5.7
        container_name: securiskan-db
        volumes:
            - ./db/:/var/lib/mysql
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: securiskan
            MYSQL_ROOT_PASSWORD: root
        networks:
            - securiskan-network

networks:
    securiskan-network:
        driver: bridge
